import { Timeline } from "../timeline";
import type {
	ObjectiveResponseRatePerBICR,
	TreatmentEvent,
} from "@/models/patient";

export const timelines: Timeline<
	ObjectiveResponseRatePerBICR,
	TreatmentEvent,
	Array<ObjectiveResponseRatePerBICR>,
	Array<TreatmentEvent>
> = [
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "MinimalResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "PartialResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 4,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 2,
				end: 4,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 4,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 4,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 4,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 5,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 5,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 5,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 5,
				end: 7,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 1,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 5,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 5,
				end: 7,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 5,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 5,
				end: 7,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 0,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 5,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 5,
				end: 8,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 8,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 9,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 8,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 0,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 0,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 9,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 9,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 7,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 7,
				end: 9,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 9,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 5,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 5,
				end: 9,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 1,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 0,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 0,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 1,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 7,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 10,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 8,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 10,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 9,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 10,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 10,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 7,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 4,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 4,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 4,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 4,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 11,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 5,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 5,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 5,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 8,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 8,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 4,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 4,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 5,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 5,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 8,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 8,
				end: 12,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 4,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 4,
				end: 12,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 12,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 12,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 11,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 11,
				end: 12,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 10,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 10,
				end: 12,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 8,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 8,
				end: 12,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 13,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 13,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 13,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 2,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 2,
				end: 7,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 7,
				end: 13,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 5,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 5,
				end: 13,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 13,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 14,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 14,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 14,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 12,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 12,
				end: 15,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 0,
				end: 1,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 1,
				end: 3,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 3,
				end: 18,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
	{
		eventKinds: [],
		intervalKinds: [],
		events: [],
		intervals: [
			{
				start: 1,
				end: 6,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 6,
				end: 12,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
			{
				start: 12,
				end: 19,
				tag: "time-interval",
				kind: "CompleteResponse",
				description: "generic-description",
			},
		],
	},
];
